### ISSUE TITLE
Select and Cancel buttons are reversed in the file chooser dialog

### ISSUE THREAD

**Issue by danirabbit** [heisantosh/qrshare#15]
The order should be:

[ Cancel ] [ Select ]

Currently it is:

[ Select ] [ Cancel ]

See [this HIG entry on dialogs](https://elementary.io/docs/human-interface-guidelines#dialogs)

**Comment by heisantosh** [comment]
I've made a new release 0.7.6 to fix this issue. It is currently on review on AppCenter dashboard.

**Comment by heisantosh** [comment]
App is now available in the AppCenter with the correct button order [Cancel] [Select]
