### ISSUE TITLE
does not work with multiple file shares

### ISSUE THREAD

**Issue by js-d-coder** [heisantosh/qrshare#17]
I was trying to share multiple images by selecting them all and right clicking for QR Share. It turns out, it is sharing one file more than once, the first file in the selection.  
Thanks for the software, please let me know if you want more technical details...

**Comment by heisantosh** [comment]
Glad that you are using it. I'll try to release a fix in the weekend.

**Comment by js-d-coder** [comment]
See? It is sharing one file twice, instead of sharing two different files.  
Also I would like to request one feature: clicking on 'Stop Sharing' on one file shouldn't stop sharing other too.
![screenshot from 2017-12-03 13-46-25](https://user-images.githubusercontent.com/23054879/33523561-86edc524-d830-11e7-8f94-e8eb8c11d2c5.png)

**Comment by heisantosh** [comment]
That's right. The issue with the current implementation is the app runs runs with a single instance. So trying to open another window uses the same values.
I'll be doing a major update tonight or tomorrow morning. Took a couple of weeks to fix as I'm including new features. Should be a major update. 

Here is a sneak peek ;) -

<img src="https://raw.githubusercontent.com/mubitosh/qrshare/master/data/screenshot-qr-window.png">

<img src="https://raw.githubusercontent.com/mubitosh/qrshare/master/data/screenshot-shared-link-1.png">

**Comment by js-d-coder** [comment]
well this looks cool, sharing an entire folder.... I hope I will be able to open this share on my Android by putting this address in its browser

**Comment by heisantosh** [comment]
Yep, you can access on Android also by using a web browser.

**Comment by js-d-coder** [comment]
Got the update, have 1 question and 1 suggestion:

Q: I copied the address it provides on sharing and pasted in File's 'Connect to Server', does not connect. It does connects from Android Browser, awesome work!

S: You can put download button below each item or send some kind of header what will prevent browsers opening the item and instead start downloading...

**Comment by heisantosh** [comment]
Since it's not an FTP or SSH server, it can't be used with Files' 'Connect to Server'. The app provides a web interface, so it should be accessed with a web browser.
I might be looking into other enhancements/features in the future. Until then, we have to wait :)
