### ISSUE TITLE
Don't use Pokemon as your icons

### ISSUE THREAD

**Issue by danirabbit** [heisantosh/qrshare#6]
Pokemon is a registered trademark of Nintendo and The Pokemon Company.

**Comment by heisantosh** [comment]
My bad. I think I'll dig through devianart to find some icons.

**Comment by heisantosh** [comment]
Using the available icons in the system: x-text-preview and system-file-manager. I think it's better suited.

![screenshot from 2017-09-06 08-35-54](https://user-images.githubusercontent.com/5291239/30092755-7c810c32-92de-11e7-85de-69b067522dcf.png)
