### ISSUE TITLE
Binaries must be built through AppCenter Dashboard

### ISSUE THREAD

**Issue by danirabbit** [heisantosh/qrshare#7]
You cannot publish a binary built on your own computer. Binaries must be built by packaging on elementary's AppCenter Dashboard servers

**Comment by heisantosh** [comment]
Starting to use [gb](https://getgb.io/) to manage the project. I think it should let me build binaries in AppCenter server.

**Comment by heisantosh** [comment]
Release 0.7.4 got built successfully in AppCenter.

**Comment by danirabbit** [comment]
it looks like you're still installing a pre-built binary onto users systems: https://github.com/mubitosh/qrshare/blob/master/bin/meson.build

**Comment by heisantosh** [comment]
That's an empty file which acts as a placeholder. I created using `touch com.github.mubitosh.qrshare`. It gets overwritten by the actual binary after the build that happens in AppCenter.

**Comment by heisantosh** [comment]
Anyways, I'm using this now instead

meson/build.sh builds and renames the binary

```bash
gb build -tags gtk_3_18 all
mv bin/qrshare-gtk_3_18 bin/com.github.mubitosh.qrshare
```

In debian/rules create bin directory and copy the binary built above
```bash
override_dh_auto_install:
	cd debian/build && DESTDIR=${CURDIR}/debian/com.github.mubitosh.qrshare ninja install
	mkdir -p debian/com.github.mubitosh.qrshare/usr/bin
	cp bin/com.github.mubitosh.qrshare debian/com.github.mubitosh.qrshare/usr/bin/
```
I'm removing the bin directory with the placeholder from the project.
